name: AdaptiveAgents

# ======================== Agent's Hyperparameter ========================
# The initial hyperparameters of the population
hp_initial:
  strength_mutation: 0.1
do_include_fruit: True
do_include_value_global: True
do_include_value_fruit: True
do_include_novelty_hunger: True
list_channels_visual_field: ${env.list_channels_visual_field}

# ======================== Evolution Hyperparameters ========================
mode_weights_transmission: none # initial, final, none

# The dimension of the latent space corresponding to the internal representation of each fruit map
n_latent_fruit: 11

# The configuration of the decision model
decision_model:
  hidden_dims: []

# ======================== Models Config ========================

# The configuration of the reward model
reward_model:
  func_weight: hardcoded # constant, linear, hardcoded, one
  dict_reward:
    energy: ${eval:'${env.energy_max} / (${env.energy_food} - 1)'} # set the reward of eating a plant to 1
    age: 0
    n_childrens: ${eval:'1.0 * ${env.energy_cost_reprod} * ${env.energy_max} / (${env.energy_food} - 1)'} 



# ======================== Defaults sub-configs and other Hydra config ========================
defaults:
  - _self_
  - metrics : base_agents_metrics