name: RL_Agents
hp_initial:
  lr: 0.001
  gamma: 0.99
  epsilon: 0.1
  strength_mutation: 0.001
mode_weights_transmission: final # initial, final, none
name_exploration: epsilon_greedy
reward_model:
  func_weight_diff: constant # constant, linear, exponential

# ======================== Defaults sub-configs and other Hydra config ========================
defaults:
  - _self_
  - metrics : basic