name: AdaptedCNN
cnn_config:
  # hidden_dims: [32, 16, 8]
  hidden_dims: []
  kernel_size: 3
  strides: 1
range_nearby_pixels: 1
mlp_config:
  hidden_dims: []
  n_output_features: 5

# This does the following:
# - CNN(s) : (H, W, C) -> ... -> (H, W, last_hidden_dim) -> (H*W*last_hidden_dim,) -> (dim_cnn_output,)
# - MLP : (dim_cnn_output,) concat with other obs -> MLP -> (n_output_features,)