name: RegionalModel
weighting_method: "uniform"
mlp_region_config:
  hidden_dims: []
  n_output_features: 1 # must be 1
mlp_config:
  hidden_dims: []
  n_output_features: 5
# This does the following:
# - CNN(s) : (H, W, C) -> ... -> (H, W, last_hidden_dim) -> (H*W*last_hidden_dim,) -> (dim_cnn_output,)
# - MLP : (dim_cnn_output,) concat with other obs -> MLP -> (n_output_features,)