name: RegionalModel
weighting_method: "uniform"
mlp_region_config:
  hidden_dims: [10]
  n_output_features: 1 # must be 1
mlp_config:
  hidden_dims: [10]
  n_output_features: ${n_actions} # if same numbeer as n_actions, no dense layer will be added by BaseModel