# Hyperparameters
seed: 
n_timesteps : 100000
# period_eval : ${eval:'${n_timesteps} / 500'}
period_eval : 50
n_agents_max : 10
# n_agents_initial : ${n_agents_max}
n_agents_initial : 2
do_jit: True
n_actions: ${eval:'len(${env.list_actions})'}



# Logging
# do_wandb : False
# wandb_config:
#   project : EcoJAX
# do_tb : True
# do_cli : False
# do_csv : True
# do_tqdm : True
# do_snakeviz : True
# do_render : True
# do_global_log : True

do_wandb : False
wandb_config:
  project : EcoJAX
do_tb : True
do_cli : False
do_csv : False
do_tqdm : True
do_snakeviz : True
do_jax_prof : False
do_render : True
do_global_log : True



# Defaults sub-configs and other Hydra config.
defaults:
  - _self_
  - env : test_env
  - agents : ada_r_hc
  - model : region
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 



# Hydra config, do not change.
hydra:
  output_subdir: null
  run:
    dir: .