# ======================== Measures ========================
measures:
  global: 
    - params_agents
  immediate:
    - reward
  state:
    - hp
    - params_reward_model
    - weights_agents
    - loss_q
    - q_values_max
    - q_values_min
    - q_values_mean
    - q_values_median
    - target
    - gradients weights
    - gradients bias
  behavior: []

aggregators_lifespan:
  - class_string : ecojax.metrics.aggregators:AggregatorLifespanCumulative
    config:
      keys_measures : ${agents.metrics.measures.immediate}
      n_agents : ${n_agents_max}
      prefix_metric : life_cum
      log_final : true
  - class_string : ecojax.metrics.aggregators:AggregatorLifespanAverage
    config:
      keys_measures : ${merge:${agents.metrics.measures.immediate}, ${agents.metrics.measures.state}, ${agents.metrics.measures.behavior}}
      n_agents : ${n_agents_max}
      prefix_metric : life_avg

aggregators_population:
  - class_string : ecojax.metrics.aggregators:AggregatorPopulationMean
    config:
      keys_measures : ${merge:${agents.metrics.measures.immediate}, ${agents.metrics.measures.state}, ${agents.metrics.measures.behavior}}
      keys_measures_prefix : [life, weights, params_reward_model, hp]
      n_agents : ${n_agents_max}
      prefix_metric : pop_mean
